# Generated by Django 3.0.4 on 2020-04-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=45)),
                ('activity_content', models.CharField(max_length=200)),
                ('activity_join', models.IntegerField()),
                ('activity_deadline', models.DateTimeField()),
                ('activity_num', models.IntegerField()),
                ('activity_maxnum', models.IntegerField()),
                ('activity_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
