# Generated by Django 3.0.4 on 2020-05-13 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20200413_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_content',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_time',
            field=models.DateTimeField(),
        ),
    ]
