# Generated by Django 3.0.4 on 2020-04-27 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reward', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user_has_reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_time', models.DateTimeField(auto_now_add=True)),
                ('finish', models.BooleanField(default=0)),
                ('finish_time', models.DateTimeField(auto_now_add=True)),
                ('reward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reward', to='reward.Reward')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reweard_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_has_reward',
            },
        ),
    ]
