# Generated by Django 3.0.4 on 2020-05-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_has_reward', '0002_auto_20200513_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_has_reward',
            name='num',
            field=models.IntegerField(default=1),
        ),
    ]
