# Generated by Django 3.0.4 on 2020-04-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_name', models.CharField(max_length=45)),
                ('reward_content', models.CharField(max_length=200)),
                ('reward_join', models.IntegerField()),
                ('reward_num', models.IntegerField()),
            ],
            options={
                'db_table': 'reward',
            },
        ),
    ]
